### ISSUE TITLE
To-Do Reference

### ISSUE THREAD

**Issue by jordan-sullivan** [kendallm360/cocktail-lounge#23]
- [x] 1) get details for amaretto rendering

- [x] 2) get details for random drinks rendering

**^^BY EOD Friday** 

- [x] 3) Basic css, Cypress testing, Error Handling, re-check the rubric to see if on track

**^^BY EOD Saturday**

- [x] 4) Refactor, Hooks, final css, bourbon? , re-visit our proposal for Scott 

** BY EOD Sunday**

- [x] 5) ReadMe, TBD Monday
